---
- name: Install Prometheus and Grafana
  hosts: all
  become: yes
  tasks:
    - name: Copy the Python script to the remote host
      community.docker.docker_compose_v2:
        project_src:: ../monitoring
        state: present