---
- name: Install Prometheus and Grafana
  hosts: all
  become: yes
  tasks:
    - name: Copy the Monioring Configuration to remote host
      copy:
        src: ../monitoring/
        dest: /home/ubuntu/monitoring/
        mode: '0755'
    - name: Run docker compose to setup monitoring
      command: cd  /home/ubuntu/monitoring && docker-compose up -d